name: GitHub Actions Demo
on: [push]
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ./Dockerfile -t home-lc .
      - run: docker tag home-lc registry.xilin.icu/home-lc
      - run: docker push registry.xilin.icu/home-lc
      # - name: deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: root
      #     key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
      #     # script: docker pull registry.xilin.icu/nginx-test && docker rm $(docker ps -aq) -f && docker run -p 8083:80 --rm -d registry.xilin.icu/nginx-test
      #     script: docker-compose pull && docker-compose up -d --force-recreate
